; Flash: 4MB QD, PSRAM: 8MB OT
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial monitor settings
monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

; IMPORTANT: Exclude ui_sources.c
build_src_filter = +<*> -<ui_sources.c>
lib_deps = 
	lovyan03/LovyanGFX@^1.2.26
	lvgl/lvgl@8.3.11